# Generated by Django 6.0.6 on 2026-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('billing-api', 'Billing API'), ('auth-service', 'Auth Service'), ('payment-processor', 'Payment Processor'), ('notification-service', 'Notification Service')], db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], db_index=True, max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('commit_sha', models.CharField(help_text='7–40 hex chars (short or full SHA)', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
